# Generated by Django 5.1.2 on 2024-11-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
