# Generated by Django 5.1.2 on 2024-11-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0004_alter_blogpost_content_alter_project_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='difficulty',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
