# Generated by Django 5.1.2 on 2024-11-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0010_progressreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='wiki_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='wiki_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
