# Generated by Django 5.1.2 on 2024-11-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0011_project_wiki_url_task_wiki_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='wiki_url',
            new_name='github_repo_url',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='wiki_url',
            new_name='github_issue_url',
        ),
        migrations.AddField(
            model_name='project',
            name='github_wiki_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
